### ISSUE TITLE
"Download" button on home page is effectively broken for some(or many or most?) users

### ISSUE THREAD

**Issue by broofa** [openrocket/openrocket.github.io#12]
## Current behavior

Clicking the "Download" button at the top of https://openrocket.info downloads the OpenRocket `.jar` file.  However, as noted on the [Releases page](https://github.com/openrocket/openrocket/releases)...
> If you have a more recent version [of Java] on your computer (as nearly everyone does), you will not be able to run the .jar file below without downgrading

**This caveat does not appear anywhere on the home page!**

OpenRocket will fail to run for users experiencing this problem, and will fail in incomprehensible ways, as evidenced by https://github.com/openrocket/openrocket/issues/759.

## Desired Behavior

For most users, the `.jar` file is (and should be) the option of last resort.  Windows and Mac users almost certainly prefer `.exe` or `.dmg` installations, respectively.  And Linux users may prefer `.AppImage` installations, although I'm not as familiar with that community so can't be sure about that.

Ideally the "Download" button would cause the appropriate installer (.exe, .dmg, .AppImage) to download based on the user's OS.  Failing that, taking the user's to the Github Releases page where they will at least be apprised of the `.jar` issue, and can select the appropriate installer for themselves will avoid this unpleasantness.

**Comment by wolsen** [comment]
Thanks for raising this. We definitely should look at improving our download experience. I'll add this to the list of things to look at when getting the next release out.

**Comment by wolsen** [comment]
This should resolved with #13.
