### ISSUE TITLE
Rename 'Packages and Source Code' + change home page download button behavior

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket.github.io#19]
I would opt to rename the nav-bar 'Packages and Source Code' to 'Download'. Keeps it more concise and a Download-page is most often the thing people look for.

I would also suggest to change the download button behavior. Right now (in the development branch) it downloads the JAR-version of OR, but throughout the site we state that we strongly recommend to use the packaged installer. So my suggestion: make an operating system dependent download button that e.g. for macOS systems downloads the .dmg installer + add an option to download the versions of other operating systems.

Here is an example of the Blender download page of how I would prefer the download button to be:
<img width="1299" alt="154879517-12946193-b4b4-49ce-9ebb-c71bedce6841" src="https://user-images.githubusercontent.com/11031519/154880458-e5303c94-46f1-4a63-84e8-922efb335ea8.png">

**Comment by JoePfeiffer** [comment]
I'd say that whole front page of the site needs to be completely redone. All the really useful links are hidden in tiny dropdown menus, while the actual page is devoted to advertising.
